### ISSUE TITLE
sfdisk: stack-buffer-overflow in libfdisk/src/script.c:partno_from_devname()

### ISSUE THREAD

**Issue by mrc0mmand** [karelzak/util-linux#1015]
Discovered with AFL & AddressSanitizer (using latest master of util-linux).

```
# /home/mrc0mmand/repos/util-linux/sfdisk /dev/loop0 < id:000001,sig:06,src:000018,op:arith8,pos:0,val:+14 
Checking that no-one is using this disk right now ... OK

Disk /dev/loop0: 100 MiB, 104857600 bytes, 204800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x8661a23c

Old situation:

Device       Boot Start    End Sectors Size Id Type
/dev/loop0p1       2048  22527   20480  10M 83 Linux
/dev/loop0p2      22528 204799  182272  89M 83 Linux

=================================================================
==3723974==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffbbdee6bf at pc 0x7f3cb5641b6a bp 0x7fffbbdee300 sp 0x7fffbbdedaa8
READ of size 1 at 0x7fffbbdee6bf thread T0
    #0 0x7f3cb5641b69  (/lib64/libasan.so.6+0x6bb69)
    #1 0x7f3cb5641ede in __interceptor_strtol (/lib64/libasan.so.6+0x6bede)
    #2 0x4c120b in partno_from_devname libfdisk/src/script.c:963
    #3 0x4c120b in parse_line_nameval libfdisk/src/script.c:1006
    #4 0x4c120b in fdisk_script_read_buffer libfdisk/src/script.c:1255
    #5 0x4c120b in fdisk_script_read_line libfdisk/src/script.c:1337
    #6 0x4c120b in fdisk_script_read_line libfdisk/src/script.c:1299
    #7 0x41d48b in command_fdisk disk-utils/sfdisk.c:1871
    #8 0x40a08a in main disk-utils/sfdisk.c:2379
    #9 0x7f3cb5404041 in __libc_start_main (/lib64/libc.so.6+0x27041)
    #10 0x4146fd in _start (/home/mrc0mmand/repos/util-linux/sfdisk+0x4146fd)

Address 0x7fffbbdee6bf is located in stack of thread T0 at offset 287 in frame
    #0 0x41c93f in command_fdisk disk-utils/sfdisk.c:1715

  This frame has 10 object(s):
    [32, 36) 'yes' (line 1988)
    [48, 52) 'yes' (line 1658)
    [64, 72) 'cur_partno' (line 1896)
    [96, 104) 'pa' (line 1558)
    [128, 136) 'pa' (line 1533)
    [160, 168) 'fstype' (line 1659)
    [192, 200) 'tmp' (line 1660)
    [224, 232) 'pa' (line 1416)
    [256, 264) 'data' (line 1417)
    [288, 8480) 'buf' (line 1720) <== Memory access at offset 287 underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/lib64/libasan.so.6+0x6bb69) 
Shadow bytes around the buggy address:
  0x1000777b5c80: 04 f2 04 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2
  0x1000777b5c90: 00 f2 f2 f2 00 f3 f3 f3 00 00 00 00 00 00 00 00
  0x1000777b5ca0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000777b5cb0: 00 00 00 00 f1 f1 f1 f1 04 f2 04 f2 00 f2 f2 f2
  0x1000777b5cc0: 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2
=>0x1000777b5cd0: 00 f2 f2 f2 00 f2 f2[f2]00 00 00 00 00 00 00 00
  0x1000777b5ce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000777b5cf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000777b5d00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000777b5d10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000777b5d20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3723974==ABORTING
```

Archive with two inputs causing the issue: [sfdisk-afl-input.tar.gz](https://github.com/karelzak/util-linux/files/4534955/sfdisk-afl-input.tar.gz)

**Comment by karelzak** [comment]
Fixed, thanks for your report.
