### ISSUE TITLE
sfdisk: Floating point exception in lib/strutils.c:199

### ISSUE THREAD

**Issue by mrc0mmand** [karelzak/util-linux#1017]
After #1015 was fixed I twiddled with the AFL knobs a little bit and unleashed it once again, which triggered following FPE (after 4+ hours):

```
# ~/util-linux/sfdisk -n /dev/loop0 < id\:000001\,sig\:06\,src\:000566+000660\,op\:splice\,rep\:16 
Disk /dev/loop0: 100 MiB, 104857600 bytes, 204800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

AddressSanitizer:DEADLYSIGNAL
=================================================================
==2306564==ERROR: AddressSanitizer: FPE on unknown address 0x00000042fb69 (pc 0x00000042fb69 bp 0x0ff7c505bbd0 sp 0x7ffeac088880 T0)
    #0 0x42fb69 in parse_size lib/strutils.c:199
    #1 0x4c249a in next_number libfdisk/src/script.c:930
    #2 0x4c249a in parse_line_valcommas libfdisk/src/script.c:1176
    #3 0x4c249a in fdisk_script_read_buffer libfdisk/src/script.c:1264
    #4 0x4c249a in fdisk_script_read_line libfdisk/src/script.c:1342
    #5 0x4c249a in fdisk_script_read_line libfdisk/src/script.c:1304
    #6 0x41da35 in command_fdisk disk-utils/sfdisk.c:1871
    #7 0x40a1a6 in main disk-utils/sfdisk.c:2379
    #8 0x7fbe2bbf9041 in __libc_start_main (/lib64/libc.so.6+0x27041)
    #9 0x41465d in _start (/root/util-linux/sfdisk+0x41465d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE lib/strutils.c:199 in parse_size
==2306564==ABORTING
Aborted
```

Works without ASan as well on the Rawhide sfdisk version (util-linux-2.35.1-9.fc33.x86_64):
```
# sfdisk -n /dev/loop0 < id\:000000\,sig\:06\,src\:000542\,op\:havoc\,rep\:2            
Disk /dev/loop0: 100 MiB, 104857600 bytes, 204800 sectors
Units: sectors of 1 * 512 = 512 bytes                                                                                  
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
                                                           
Floating point exception (core dumped) 
```

Two reproducers for the issue: [sfdisk-afl-FPE.tar.gz](https://github.com/karelzak/util-linux/files/4541531/sfdisk-afl-FPE.tar.gz)

**Comment by karelzak** [comment]
Fixed. Thnaks!
