### ISSUE TITLE
sfdisk: infinite loop in lib/strutils.c:parse_size()

### ISSUE THREAD

**Issue by mrc0mmand** [karelzak/util-linux#1023]
You guessed it, another issue found by AFL. Following reproducer:

```
,1.0000000000000000000000000000018000000000000000010M
,K 
,d
```

causes an infinite loop in https://github.com/karelzak/util-linux/blob/0d5260b66c5581c8a5855a5f49e298e48e8baf82/lib/strutils.c#L174-L179

because `frac_div` overflows and eventually gets all the way back to zero:

```
(gdb) run -n /dev/loop0 < sfdisk-hang-part2
...
(gdb) p frac_div
$32 = 10000000000000000000
(gdb) p frac
$33 = 18000000000000000010
(gdb) cont
Continuing.

Breakpoint 4, parse_size (str=0x7fffffffb681 "1.", '0' <repeats 29 times>, "18", '0' <repeats 16 times>, "10M", res=0x7fffffffb580, power=0x7fffffffb578)
    at lib/strutils.c:178
178				frac_div *= 10;
(gdb) p frac_div
$34 = 7766279631452241920
(gdb) p frac
$35 = 18000000000000000010
(gdb) p (uintmax_t)-1
$36 = 18446744073709551615

(gdb) cont 30
Will ignore next 29 crossings of breakpoint 1.  Continuing.

Breakpoint 1, parse_size (str=0x7fffffffb681 "1.", '0' <repeats 29 times>, "18", '0' <repeats 16 times>, "10M", res=0x7fffffffb580, power=0x7fffffffb578)
    at lib/strutils.c:178
178				frac_div *= 10;
(gdb) p frac_div
$40 = 0

```

Original copy of the reproducer: [sfdisk-hang-part2.tar.gz](https://github.com/karelzak/util-linux/files/4559413/sfdisk-hang-part2.tar.gz)

**Comment by karelzak** [comment]
Fixed.

**Comment by evverx** [comment]
@mrc0mmand looks like you fuzzed the binaries directly but I wonder if you have any fuzz targets that can be added by analogy with https://github.com/karelzak/util-linux/pull/1068?

**Comment by mrc0mmand** [comment]
> @mrc0mmand looks like you fuzzed the binaries directly but I wonder if you have any fuzz targets that can be added by analogy with #1068?

Unfortunately not. I used the `sfdisk` and `fdisk` binaries directly and was just feeding them pre-generated inputs from AFL to test things out. I originally wanted to minimize the resulting corpora and possibly add it as another regression/sanity test (since the fuzzers were running for more than a month and the coverage was pretty good), but unfortunately the VM I used for it disappeared with all of its data due to an infra failure.

**Comment by karelzak** [comment]
> @mrc0mmand looks like you fuzzed the binaries directly but I wonder if you have any fuzz targets that can be added by analogy with #1068?

It would be nice to add libfdisk/src/fuzz_script.c :-)

**Comment by evverx** [comment]
I wrote a simple fuzz target calling `fdisk_script_read_file` and it crashed almost as soon as it started with
```
libfdisk/src/parttype.c:441:11: runtime error: member access within null pointer of type 'const struct fdisk_label'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior libfdisk/src/parttype.c:441:11 in
AddressSanitizer:DEADLYSIGNAL
=================================================================
==177148==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x000000590e28 bp 0x7ffef9cd9cd0 sp 0x7ffef9cd9c20 T0)
==177148==The signal is caused by a READ memory access.
==177148==Hint: address points to the zero page.
    #0 0x590e27 in fdisk_label_advparse_parttype /home/vagrant/util-linux/libfdisk/src/parttype.c:441:11
    #1 0x5535fb in parse_line_nameval /home/vagrant/util-linux/libfdisk/src/script.c:1086:15
    #2 0x54f0d0 in fdisk_script_read_buffer /home/vagrant/util-linux/libfdisk/src/script.c:1266:8
    #3 0x546583 in fdisk_script_read_file /home/vagrant/util-linux/libfdisk/src/script.c:1372:8
    #4 0x55023d in LLVMFuzzerTestOneInput /home/vagrant/util-linux/libfdisk/src/script.c:1552:2
    #5 0x44dc78 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x44dc78)
    #6 0x44e8a0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x44e8a0)
    #7 0x44f260 in fuzzer::Fuzzer::MutateAndTestOne() (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x44f260)
    #8 0x451607 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x451607)
    #9 0x43bdab in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x43bdab)
    #10 0x42bd36 in main (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x42bd36)
    #11 0x7f3d9a1251a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
    #12 0x42bd8d in _start (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x42bd8d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/vagrant/util-linux/libfdisk/src/parttype.c:441:11 in fdisk_label_advparse_parttype
==177148==ABORTING
```
and
```
libfdisk/src/script.c:1165:11: runtime error: division by zero
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior libfdisk/src/script.c:1165:11 in
AddressSanitizer:DEADLYSIGNAL
=================================================================
==177145==ERROR: AddressSanitizer: FPE on unknown address 0x0000005558f5 (pc 0x0000005558f5 bp 0x7fff1ba91c10 sp 0x7fff1ba91aa0 T0)
    #0 0x5558f4 in parse_line_valcommas /home/vagrant/util-linux/libfdisk/src/script.c:1165:11
    #1 0x54f0e4 in fdisk_script_read_buffer /home/vagrant/util-linux/libfdisk/src/script.c:1270:8
    #2 0x546583 in fdisk_script_read_file /home/vagrant/util-linux/libfdisk/src/script.c:1372:8
    #3 0x55023d in LLVMFuzzerTestOneInput /home/vagrant/util-linux/libfdisk/src/script.c:1552:2
    #4 0x44dc78 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x44dc78)
    #5 0x44e8a0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x44e8a0)
    #6 0x44f260 in fuzzer::Fuzzer::MutateAndTestOne() (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x44f260)
    #7 0x451607 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x451607)
    #8 0x43bdab in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x43bdab)
    #9 0x42bd36 in main (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x42bd36)
    #10 0x7f80154da1a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
    #11 0x42bd8d in _start (/home/vagrant/util-linux/out/test_fdisk_script_fuzz+0x42bd8d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE /home/vagrant/util-linux/libfdisk/src/script.c:1165:11 in parse_line_valcommas
==177145==ABORTING
```
so it looks like it would make sense to add it :-)
