### ISSUE TITLE
lsblk opens "(null)/sys/block/..."

### ISSUE THREAD

**Issue by jwilk** [karelzak/util-linux#1062]
`lsblk` tries to open files in the `(null)/sys/block/` directory:

```console
$ strace -o '| grep "(null)" >&2' lsblk >/dev/null
openat(AT_FDCWD, "(null)/sys/block/xvda/hidden", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "(null)/sys/block/xvda1/hidden", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

Backtrace:

```
#4  0x00007fbf7c18a1ea in _IO_new_fopen (filename=filename@entry=0x7ffe57827870 "(null)/sys/block/xvda/hidden", mode=mode@entry=0x55de3f73b15d "re") at iofopen.c:86
#5  0x000055de3f738dcf in sysfs_devname_is_hidden (prefix=<optimized out>, name=<optimized out>) at lib/sysfs.c:860
#6  0x000055de3f72c331 in initialize_device (name=0x55de401a1083 "xvda", wholedisk=0x0, dev=0x55de401a9050) at misc-utils/lsblk.c:1166
#7  devtree_get_device_or_new (name=0x55de401a1083 "xvda", disk=0x0, tr=0x55de4019ff00) at misc-utils/lsblk.c:1245
#8  devtree_get_device_or_new (tr=0x55de4019ff00, disk=0x0, name=0x55de401a1083 "xvda") at misc-utils/lsblk.c:1234
#9  0x000055de3f72b1b3 in process_all_devices (tr=0x55de4019ff00) at misc-utils/lsblk.c:1611
#10 main (argc=<optimized out>, argv=<optimized out>) at misc-utils/lsblk.c:2158
```

Tested with git master (8f3ce436b8e028028032a6687ec1b4f07bea7ff6).

**Comment by karelzak** [comment]
Thanks, and thanks for the backtrace. Fixed.
