### ISSUE TITLE
kill/name_to_number seems to be failing under ASan on Ubuntu Bionic

### ISSUE THREAD

**Issue by evverx** [karelzak/util-linux#1076]
According to https://travis-ci.org/github/karelzak/util-linux/jobs/702935743 the test crashes somewhere along the way on Ubuntu Bionic with
```
diff-{{{
--- /home/travis/build/karelzak/util-linux/tests/expected/kill/name_to_number	2020-06-28 18:16:56.931694123 +0000
+++ /home/travis/build/karelzak/util-linux/tests/output/kill/name_to_number	2020-06-28 18:20:51.941049571 +0000
@@ -1 +1,2 @@
-all ok
+BUS returned 0 while 7 was expected
+FPE returned 0 while 8 was expected
}}}-diff


diff-{{{
--- /dev/null	2020-06-28 18:15:54.436000000 +0000
+++ /home/travis/build/karelzak/util-linux/tests/output/kill/name_to_number.err	2020-06-28 18:20:51.941049571 +0000
@@ -0,0 +1,22 @@
+ASAN:DEADLYSIGNAL
+=================================================================
+==12070==ERROR: AddressSanitizer: SEGV on unknown address 0x07d000002f2f (pc 0x7f1565446ff7 bp 0x7fffc958df10 sp 0x7fffc958ded8 T0)
+    #0 0x7f1565446ff6 in select (/lib/x86_64-linux-gnu/libc.so.6+0x116ff6)
+    #1 0x558c30b0e25f in main tests/helpers/test_sigreceive.c:178
+    #2 0x7f1565351b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
+    #3 0x558c30b0e359 in _start (/home/travis/build/karelzak/util-linux/test_sigreceive+0x2359)
+
+AddressSanitizer can not provide additional info.
+SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x116ff6) in select
+==12070==ABORTING
+ASAN:DEADLYSIGNAL
+=================================================================
+==12099==ERROR: AddressSanitizer: FPE on unknown address 0x07d000002f4e (pc 0x7f702d4c7ff7 bp 0x7ffe1b200570 sp 0x7ffe1b200538 T0)
+    #0 0x7f702d4c7ff6 in select (/lib/x86_64-linux-gnu/libc.so.6+0x116ff6)
+    #1 0x5651b850925f in main tests/helpers/test_sigreceive.c:178
+    #2 0x7f702d3d2b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
+    #3 0x5651b8509359 in _start (/home/travis/build/karelzak/util-linux/test_sigreceive+0x2359)
+
+AddressSanitizer can not provide additional info.
+SUMMARY: AddressSanitizer: FPE (/lib/x86_64-linux-gnu/libc.so.6+0x116ff6) in select
+==12099==ABORTING
}}}-diff

         kill: name_to_number                                ... FAILED (kill/name_to_number)
```

**Comment by evverx** [comment]
Looks like it's a gcc asan bug. I'll address it by switching to gcc-10. After all, the point of switching to Trusty is to get the latest build tools.
