### ISSUE TITLE
Out of bounds heap read in fsck.minix in function get_dirsize

### ISSUE THREAD

**Issue by hannob** [karelzak/util-linux#227]
This file will cause an out of bounds read access in fsck.minix, which is part of util-linux:
https://crashes.fuzzing-project.org/fsck.minix-oob-heap-read-get_dirsize

This can be seen by compiling util-linux with address sanitizer (-fsanitize=address in CFLAGS) or with valgrind. This was found with the fuzzing tool american fuzzy lop.

Address Sanitizer stack trace:

```
==21495==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000edfe at pc 0x0000004e41b1 bp 0x7ffe910d5650 sp 0x7ffe910d5648
READ of size 2 at 0x60200000edfe thread T0
    #0 0x4e41b0 in get_dirsize /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:529:11
    #1 0x4e41b0 in read_tables /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:626
    #2 0x4e41b0 in main /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:1340
    #3 0x7f7bfc0eef9f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.20-r2/work/glibc-2.20/csu/libc-start.c:289
    #4 0x438796 in _start (/mnt/ram/util-linux/fsck.minix+0x438796)

0x60200000edfe is located 13 bytes to the right of 1-byte region [0x60200000edf0,0x60200000edf1)
allocated by thread T0 here:
    #0 0x4bf762 in __interceptor_malloc (/mnt/ram/util-linux/fsck.minix+0x4bf762)
    #1 0x4dfd3d in read_tables /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:601:17
    #2 0x4dfd3d in main /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:1340
    #3 0x7f7bfc0eef9f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.20-r2/work/glibc-2.20/csu/libc-start.c:289

SUMMARY: AddressSanitizer: heap-buffer-overflow /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:529 get_dirsize
Shadow bytes around the buggy address:
  0x0c047fff9d60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9da0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fff9db0: fa fa fa fa fa fa fa fa fa fa 01 fa fa fa 01[fa]
  0x0c047fff9dc0: fa fa 00 03 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9dd0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9de0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9df0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa fd fa
  0x0c047fff9e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==21495==ABORTING
```

**Comment by hannob** [comment]
I can't reproduce this any more so I guess it's fixed.
