### ISSUE TITLE
Out of bounds stack read in fsck.minix in function check_zone_nr (and endless loop)

### ISSUE THREAD

**Issue by hannob** [karelzak/util-linux#228]
This file will cause an out of bounds stack read when passed to "fsck.minix -a", which is part of util-linux:
https://crashes.fuzzing-project.org/fsck.minix-oob-stack-read-check_zone_nr

The "-a" parameter, which forces automatic repair, is needed, otherwise fsck.minix will hang in an endless loop (which is probably also worth fixing).

To see this one needs to compile util-linux with address sanitizer (-fsanitize=address in CFLAGS). This was found with american fuzzy lop.

Address Sanitizer error message:
```
==24937==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffec33da2c0 at pc 0x0000004ea972 bp 0x7ffec33d9960 sp 0x7ffec33d9958
READ of size 2 at 0x7ffec33da2c0 thread T0
    #0 0x4ea971 in check_zone_nr /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:305:7
    #1 0x4e69ba in map_block /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:412:11
    #2 0x4e69ba in check_file /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:939
    #3 0x4e69ba in recursive_check /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:1086
    #4 0x4e1af2 in check /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:1232:2
    #5 0x4e1af2 in main /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:1361
    #6 0x7f35dfecbf9f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.20-r2/work/glibc-2.20/csu/libc-start.c:289
    #7 0x438796 in _start (/mnt/ram/util-linux/fsck.minix+0x438796)

Address 0x7ffec33da2c0 is located in stack of thread T0 at offset 2208 in frame
    #0 0x4e629f in recursive_check /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:1073

  This frame has 3 object(s):
    [32, 1056) 'ind.i.i'
    [1184, 2208) 'dind.i.i' <== Memory access at offset 2208 overflows this variable
    [2336, 2340) 'blk_chg.i.i'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /f/util-linux/util-linux-2.27/disk-utils/fsck.minix.c:305 check_zone_nr
Shadow bytes around the buggy address:
  0x100058673400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100058673410: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100058673420: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100058673430: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100058673440: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100058673450: 00 00 00 00 00 00 00 00[f2]f2 f2 f2 f2 f2 f2 f2
  0x100058673460: f2 f2 f2 f2 f2 f2 f2 f2 04 f3 f3 f3 00 00 00 00
  0x100058673470: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100058673480: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00 f2 f2
  0x100058673490: 00 00 f2 f2 00 00 f2 f2 00 00 00 00 00 00 00 00
  0x1000586734a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==24937==ABORTING

**Comment by karelzak** [comment]
Fixed somehow :-)
