### ISSUE TITLE
out of bounds stack read in fsck.minix / function check_zone_nr

### ISSUE THREAD

**Issue by hannob** [karelzak/util-linux#373]
The attached file will cause an invalid memory read in the function check_zone_nr of "fsck.minix -f". This was found with the fuzzing tool american fuzzy lop and address sanitizer.
You need address sanitizer to see this bug (-fsanitize=address in CFLAGS).

asan stack trace:
```
==24278==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffffbc70a80 at pc 0x00000051831f bp 0x7ffffbc70180 sp 0x7ffffbc70178
READ of size 2 at 0x7ffffbc70a80 thread T0
    #0 0x51831e in check_zone_nr /mnt/ram/util-linux-2.29/disk-utils/fsck.minix.c:314:7
    #1 0x5128d7 in map_block /mnt/ram/util-linux-2.29/disk-utils/fsck.minix.c:421:11
    #2 0x5128d7 in check_file /mnt/ram/util-linux-2.29/disk-utils/fsck.minix.c:953
    #3 0x5128d7 in recursive_check /mnt/ram/util-linux-2.29/disk-utils/fsck.minix.c:1107
    #4 0x503fd1 in check /mnt/ram/util-linux-2.29/disk-utils/fsck.minix.c:1253:2
    #5 0x503fd1 in main /mnt/ram/util-linux-2.29/disk-utils/fsck.minix.c:1381
    #6 0x7f908feeb690 in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.23-r3/work/glibc-2.23/csu/../csu/libc-start.c:289
    #7 0x41a128 in _start (/mnt/ram/util-linux-2.29/fsck.minix+0x41a128)

Address 0x7ffffbc70a80 is located in stack of thread T0 at offset 2208 in frame
    #0 0x511d3f in recursive_check /mnt/ram/util-linux-2.29/disk-utils/fsck.minix.c:1088

  This frame has 3 object(s):
    [32, 1056) 'ind.i.i'
    [1184, 2208) 'dind.i.i' <== Memory access at offset 2208 overflows this variable
    [2336, 2340) 'blk_chg.i.i'
```
[fsck.minix-heap-oob-check_zone_nr.zip](https://github.com/karelzak/util-linux/files/600294/fsck.minix-heap-oob-check_zone_nr.zip)

**Comment by rudimeier** [comment]
Thanks for you report. I can reproduce that. 

Just being curious. What was your `configure/make` command and `afl-fuzz` command to find this bug?

**Comment by hannob** [comment]
Something like this should do:
```
export AFL_USE_ASAN=1
./configure CC=afl-clang-fast CXX=afl-clang-fast++ --disable-shared
make
afl-fuzz -i [input_dir] -o [output_dir] -m none -t 5000 [path_to]/fsck.minix -f @@

**Comment by cgoesche** [comment]
Fixed in https://github.com/util-linux/util-linux/commit/51b4b398707497daa048a859bac59925921b101d, so closing.
