### ISSUE TITLE
stack-buffer-overflow (READ of size 341) while reading malformed /var/log/wtmp

### ISSUE THREAD

**Issue by geeknik** [karelzak/util-linux#715]
This bug is present in code built from `commit e1686b25acdedb34cc357f08f0dd3ca01c559dfd`, compiled with Clang 8 and ASan on Debian 9.

Command line:
```
echo "MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MHIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwcjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw" | base64 -d | tee /var/log/wtmp && last
```

Console output:
```
root     zzs/0        104.12*?          Thu Nov  8 16:54    gone - no logout
=================================================================
==2839==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fb0649a52d0 at pc 0x00000044797a bp 0x7ffd986c33d0 sp 0x7ffd986c2b70
READ of size 341 at 0x7fb0649a52d0 thread T0
    #0 0x447979 in __interceptor_getpwnam /b/swarming/w/ir/kitchen-workdir/src/third_party/llvm/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1872:5
    #1 0x4f738f in is_phantom /root/util-linux/login-utils/last.c:603:7
    #2 0x4f738f in process_wtmp_file /root/util-linux/login-utils/last.c:824
    #3 0x4f738f in main /root/util-linux/login-utils/last.c:1027
    #4 0x7fb067b172e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
    #5 0x41dda9 in _start (/root/util-linux/last+0x41dda9)

Address 0x7fb0649a52d0 is located in stack of thread T0 at offset 720 in frame
    #0 0x4f571f in main /root/util-linux/login-utils/last.c:899

  This frame has 11 object(s):
    [32, 80) 'path.i.i' (line 598)
    [112, 116) 'loginuid.i.i' (line 608)
    [128, 272) 'st.i.i' (line 619)
    [336, 720) 'ut.i' (line 635)
    [784, 792) 'lastdown.i' (line 642) <== Memory access at offset 720 partially underflows this variable
    [816, 824) 'begintime.i' (line 643) <== Memory access at offset 720 partially underflows this variable
    [848, 992) 'st.i' (line 647) <== Memory access at offset 720 partially underflows this variable
    [1056, 1060) 'quit.i' (line 648) <== Memory access at offset 720 partially underflows this variable
    [1072, 1104) 'timestr.i' (line 879)
    [1136, 1208) 'ctl' (line 900)
    [1248, 1256) 'p' (line 909)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /b/swarming/w/ir/kitchen-workdir/src/third_party/llvm/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1872:5 in __interceptor_getpwnam
```

**Comment by karelzak** [comment]
Fixed. Thanks for your report!
