### ISSUE TITLE
heap-buffer-overflow (READ of size 4) in main (readprofile.c:283)

### ISSUE THREAD

**Issue by geeknik** [karelzak/util-linux#717]
This bug is present in code built from commit e1686b25acdedb34cc357f08f0dd3ca01c559dfd, compiled with Clang 8 and ASan on Debian 9.

Command line:

`touch test.profile && readprofile -i -p test.profile`

Console output:
```
==10436==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000650 at pc 0x0000004f76f0 bp 0x7fff741eac50 sp 0x7fff741eac48
READ of size 4 at 0x602000000650 thread T0
    #0 0x4f76ef in main /root/util-linux/sys-utils/readprofile.c:283:9
    #1 0x7f7d233df2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
    #2 0x41d979 in _start (/root/util-linux/readprofile+0x41d979)

0x602000000651 is located 0 bytes to the right of 1-byte region [0x602000000650,0x602000000651)
allocated by thread T0 here:
    #0 0x4c6123 in __interceptor_malloc /b/swarming/w/ir/kitchen-workdir/src/third_party/llvm/compiler-rt/lib/asan/asan_malloc_linux.cc:146:3
    #1 0x4f56ae in xmalloc /root/util-linux/./include/xalloc.h:32:21
    #2 0x4f56ae in main /root/util-linux/sys-utils/readprofile.c:250
    #3 0x7f7d233df2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /root/util-linux/sys-utils/readprofile.c:283:9 in main
```

**Comment by karelzak** [comment]
Fixed. Thanks for your report.
