### ISSUE TITLE
col: invalid write triggers segfault in flush_line()

### ISSUE THREAD

**Issue by geeknik** [karelzak/util-linux#749]
This fault was triggered in code built from 70c364b4db6530ada12f7103b5c5d8ceb777307f on Debian 9 with Clang 9 and `-fsanitize=address`. 

```
col: Invalid or incomplete multibyte or wide character
 @7=2F2=7F ==7F ng. @7:=2F2=7< F    @7=1
AddressSanitizer:DEADLYSIGNAL
=================================================================
==25128==ERROR: AddressSanitizer: SEGV on unknown address 0x7fa0ac725b58 (pc 0x0000004fbc27 bp 0x7ffd8e814080 sp 0x7ffd8e814030 T0)
==25128==The signal is caused by a WRITE memory access.
    #0 0x4fbc26 in flush_line /root/util-linux/text-utils/col.c:498:22
    #1 0x4fa205 in flush_lines /root/util-linux/text-utils/col.c:427:4
    #2 0x4fa205 in main /root/util-linux/text-utils/col.c:401
    #3 0x7fa0af4fd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #4 0x41e0b9 in _start (/root/util-linux/col+0x41e0b9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/util-linux/text-utils/col.c:498:22 in flush_line
==25128==ABORTING
```

col from util-linux 2.32.1 installed on Fedora 29 also segfaults with the attached reproducer.

[test0000.col.gz](https://github.com/karelzak/util-linux/files/2825164/test0000.col.gz)

**Comment by karelzak** [comment]
Fixed, but it's really not ideal bugfix. The code need rewrite to be more robust...
